name: Compile Tor for Linux on Ubuntu LTS

on:
  workflow_dispatch:
  schedule:
    - cron: "* * */1 * *"

jobs:
  compile-tor:
    - name: Compile Tor
    run: |
      apt update
      apt install -y git build-essential automake libevent-dev libssl-dev zlib1g-dev
      git clone https://git.torproject.org/tor.git
      cd tor
      ./autogen.sh
      ./configure --disable-asciidoc
      make

    - name: Release Tor Binary
    uses: softprops/action-gh-release@v1
      with:
        tag_name: tor-ubuntu
    files: |
      tor/src/app/tor
