# This workflow builds the listener docker image.
# Issues with this workflow indicate an error with the Dockerfile or with the listener package.
name: Docker build test

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag listener:$(date +%s)
