name: Release Linux & Windows binaries

on:
  push:
    branches: [ main, release-publish ]
  schedule:
    - cron: "* */6 * * *"

jobs:
  linux-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r client/requirements.txt
    - name: Build client.py
      run: |
        cd client
        wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz -O upxfiles.tar.xz
        tar -xf upxfiles.tar.xz
        python build.py
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: linux-latest
        files: |
          client/dist/client
          
  windows-release:        
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r client\requirements.txt
    - name: Build client.py
      run: |
        cd client
        python build.py
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: win-latest
        files: |
          client\dist\client.exe
